### ISSUE TITLE
X से पता चला etc.

### ISSUE THREAD

**Issue by aryamanarora** [aryamanarora/carmls-hi#20]
> मुझे धीरे-धीरे उसकी बातों **से** सब कुछ पता चला।
> I-DAT slowly he-GEN talks **ABL** all something knowledge go-PFV
> I slowly came to know everything **from** what he said.

Source? Explanation\~Source? Causer~Source?

I guess the third one would require a rephrasing where ने is possible (since that can also be Causer), but that doesn't appear to be possible.

**Comment by nitinvwaran** [comment]
Leaning against Explanation, based on these examples from the English Guidelines: 

I went outside because_of the smell. (I went outside -> WHY -> the smell)
The rain is due_to a cold front (The rain -> WHY -> a cold front)
He reacted out_of anger  (He reacted -> WHY -> anger)
I joined a protest after the shameful vote in Congress (I joined a protest -> WHY -> the shameful vote in Congress)
Her popularity has grown since she announced a bid for president (Her popularity has grown -> WHY -> she announced a bid for President)
I will appoint him since he is most qualified for the job (I will appoint him -> WHY -> he is most qualified for the job)

However:
सब कुछ पता चला -> WHY -> उसकी बातों 
feels odd to me. 

Just exploring this more, if i add the के कारण से / के कारण in lieu of से in the original, it seems to feel odd (this is also the opinion of another Hindi speaker i know whose Hindi is better than mine!) 
?*मुझे धीरे-धीरे उसकी बातों **के कारण से** सब कुछ पता चला।

Suggesting that the two phrases are not linked by an explanation?

**Comment by nitinvwaran** [comment]
Causer actually makes sense to me if it comes down to Explanation versus Causer, but from what i've read in the Guidelines, Causer seems to currently apply to inanimate things, or entities (conceptualized as forces), whereas उसकी बातों is definitely an abstract thing?

Source for the function makes sense to me based on this example from the English Guidelines: 
We discovered he was French **from** his attire. 

Other than that 'his attire' is a concrete thing while उसकी बातों is abstract, the example and the Hindi sentence seem to be very close parallels.

**Comment by aryamanarora** [comment]
I agree Explanation seems wrong. Causer too, since it's not some inanimate agent or force. I really don't like Source as the scene role... but yes, seems to be perfect for function, since this is an ablative case. To be honest, I'm not even sure about that guidelines example, since there's not starting point or initial state that is involved in that use of `from`.

Another idea: Stimulus~Source? मुझे is an Experiencer~Recipient, and the counterpart of Experiencer is Stimulus.

**Comment by nitinvwaran** [comment]
There may be a solution in the book _Modern Hindi Grammar_ by Omkar N Koul (2009 edition), published by Indian Institute of Language Studies. According to him, quoting from page 103 on compound verbs: 

> Compound verbs in Hindi are combination of Verb 1 + Verb 2 (+ inflections). Whereas Verb 1 (also called main verb) expresses general meaning and occurs in its stem form, verb 2, which is called an explicator/operator, takes all the inflections. The explicators belong to a small group of verbs. The original meaning of the explicator is lost. They add certain aspectual values, such as completion of an action, benefaction, or intensification, to the main verb

Attaching some data for some explicators from the book, full list is on page 103-104:

> Explicators | Explicators (English) | Aspectual Value
> जा | go | change of state
> जा | go | direction away, simple completion
> चल | walk | direction away, completion

Unsure if पता चला is a compound verb or a Conjunct verb, but पता चल जाना can also be studied, which is likely a compound verb. In the latter case also, the aspect is one of 'direction away, simple completion'. This might suggest that the Scene is really Source too...

**Comment by aryamanarora** [comment]
I am starting to think it is Source~Source now as well. Consider:

> मैंने अपने दोस्त **से** सीखा।

I think we can agree that this is Originator~Source, seeing as the friend is transferring knowledge, and is the source of that knowledge. Originator since he is animate. Slightly different:

> मैंने अपने दोस्त की किताब **से** सीखा।

The only difference in this sentence is that the source of knowledge is not a person but rather an object. This is parallel to the first example, just with that difference. I think this is a good argument for Source as the entity or action from which knowledge is gleaned.

And as for Stimulus/Topic: **The actual knowledge/perception is not the book itself, but the contents of the book**. That's why we can say e.g. मैंने किताब से हिंदी सीखी, where Hindi is a Topic~Theme, and the book is just a Source. So I think that's a good argument against Stimulus or Topic.

So पता चलना is definitely a compound/conjunct verb (I think both of those mean the same thing), since it's a N + V compound. जाना is an aspectual marker, indicating more information on how the verb takes place. It's really hard to describe what these do in English, but to me जाना really highlights the completion of an action here, i.e. indicates [telicity](https://en.wikipedia.org/wiki/Telicity). I don't think the presence of it really affects the reading; if we got rid of it, I still think Source would be a good label.

**Comment by nitinvwaran** [comment]
I tried another test for Source and asked a native Hindi speaker here for his judgement on these sentences:

> क्या पता चला - what [did you] come to know
> कहा से पता चला - where **से** [did you] come to know

He mentioned both are acceptable, and its interesting that the word loosely used with the से is 'where', which is locus-like.

If we try:
> *क्या से पता चला 

It feels wrong, so the word in that position may not be thematic (which words are probably answerable with क्या questions). 
Removal of thematic possibility would naturally exclude Stimulus / Topic to my thinking. 
Note किससे पता चला is fine but i always think of the किस as a person or animate thing, for which बातों may not fit. I have a hard time appropriating a 'what' to किससे.

So i think in the end i'm going with Source, after having applied Sherlock Holmes' razor to my mental satisfaction: " When you have eliminated the impossible, whatever remains, however improbable, must be the truth." :)

**Comment by aryamanarora** [comment]
Makes sense to me! Going to close the issue. We have agreed on:

* **Source\~Source** (when X is inanimate)
* **Originator\~Source** (when X is animate)
