### ISSUE TITLE
`NONSNACS` cleanup & vālā

### ISSUE THREAD

**Issue by lgessler** [aryamanarora/carmls-hi#29]
The validator expects the supersense columns to be blank in this case.

**Comment by nitinvwaran** [comment]
Removed 71 instances with NONSNACS labels. More updates on this can be found in #31. Closing this if nothing else.

**Comment by lgessler** [comment]
@nschneid did you want anything in particular to be done with these? I think I remember you saying you ideally wanted them to be annotated somehow instead of just blanked out.

**Comment by nitinvwaran** [comment]
No. They are blanked out. This resolves some of the "Invalid supersense(s) in lexical entry" issues with the validator.

**Comment by nitinvwaran** [comment]
OK, so i did a quick analysis, have attached an excel sheet with some reasons why we decided to mark these NONSNACS. If any of these reasons merits a new SNACS label, do let us know. The analysis is in the 'analysis' tab.

@aryamanarora , there are a couple of cases that I think may not be NONSNACS, we will need to revisit:
1) lp_hi_10_74 - 'ke layak' 
2) lp_hi_2_40 - 'to' - possibly FOCUS.
3) 'vaalaa' in 'teach-ER' like constructions. In the LPP this is mostly 'batti vaalaa' or 'lamp-light-ER'. There is [a definition](https://dsal.uchicago.edu/cgi-bin/app/caturvedi_query.py?qs=%E0%A4%B5%E0%A4%BE%E0%A4%B2%E0%A4%BE&searchhws=yes) that translates to "a suffix denoting an agent, doer, owner, possessor, keeper or inhabitant". It's just that i'm not sure if the vala is present in a governor-object construction here, it may just be marking the lamp as something being 'kept' by the batti vaalaa and denoting someone responsible for the lamps. If we think the predicate itself (to keep? own? light? ) can be implied in this 'batti vaala' construction, then it needs a SNACS label. Otherwise, i don't know. 

If you could also take a look at the sheet to see if my analysis makes sense :). 

[NONSNACS.xlsx](https://github.com/aryamanarora/carmls-hi/files/8980044/NONSNACS.xlsx)

**Comment by nitinvwaran** [comment]
> 'vaalaa' in 'teach-ER' like constructions. In the LPP this is mostly 'batti vaalaa' or 'lamp-light-ER'. There is [a definition](https://dsal.uchicago.edu/cgi-bin/app/caturvedi_query.py?qs=%E0%A4%B5%E0%A4%BE%E0%A4%B2%E0%A4%BE&searchhws=yes) that translates to "a suffix denoting an agent, doer, owner, possessor, keeper or inhabitant". It's just that i'm not sure if the vaalaa is present in a governor-object construction here, it may just be marking the lamp as something being 'kept' by the batti vaalaa and denoting someone responsible for the lamps. If we think the predicate itself (to keep? own? light? ) can be implied in this 'batti vaala' construction, then it probably needs a SNACS label? Otherwise, i don't know.

Propose Characteristic ~ Identity for such cases of vaalaa.

**Comment by nschneid** [comment]
Are you sure it is a postposition and not some other kind of suffixal morpheme?

**Comment by nitinvwaran** [comment]
It's not a suffixal morpheme, it's a token in its own right. But i'm not sure if it qualifies to be a postposition in the SNACS sense. The sense i got from the English guidelines is that a postposition is between a governor (usually a predicate) and an object ( argument of predicate).  

The 'batti vaalaa' is a bit more complicated, because it literally translates to 'lamp vaalaa' . But a speaker of Hindi would automatically imply that a) the term 'batti vaala' is referring to a person in the world, and b) That person is associated with the lamp in some capacity. The capacity can be implicit , as in the example 'batti vaala' or it can be explicit, as in 'batti jalaane vaala' literally [lamp light.INF vaalaa] where light is the predicate 'to light'. Maybe in english, this is: "The vaala who lights the lamp".  Kachru's grammar book calls the latter use a Particle.

**Comment by lgessler** [comment]
@nschneid in case it's relevant, it might be helpful to note that this _vālā_ morph also uses standard adjective inflections. _vālā_ covers masculine singular nominative, but it would be e.g. _vāle_ for masculine singular oblique:

```
battī vāle ko  batāo ...
lamp  VALA DAT tell ...
'tell the lampman ...'
```

My 2c: I don't have a strong opinion at the moment but it's worth considering whether only _some_ uses of _vālā_ should be considered postpositional and/or SNACS-y, as I think you already have.

**Comment by nitinvwaran** [comment]
> @nitinvwaran do you have a link to the Chaturvedi paper you're referring to?

It's not a paper, it's a [dictionary entry](https://dsal.uchicago.edu/cgi-bin/app/caturvedi_query.py?qs=%E0%A4%B5%E0%A4%BE%E0%A4%B2%E0%A4%BE&searchhws=yes) written by Chaturvedi...

I did find some [Phrase Structure Annotation Guidelines](https://verbs.colorado.edu/hindiurdu/guidelines_docs/PhraseStructureguidelines.pdf) which mentions the following:
1. vaala is mentioned as a suffix by the authors
2. It conjoins with nouns (Case I, below) or verbs (Case II) to form adjectives or even nouns. 
3. It is also used as an aspectual TAM in a verbal construction (Case III)
4. It is tagged as a post-position in the entire treebank 
5. Some syntactic analyses are provided in Section 19.4 of the tagging guidelines. I've attached the snapshot of trees below:

![vaala-1](https://user-images.githubusercontent.com/35068157/177403040-42870344-6747-4f39-86fe-9b9354e90b19.png)
![vala-2](https://user-images.githubusercontent.com/35068157/177403047-2d7b93c3-2adf-4b44-ab22-7b606b320d4a.png)

**Comment by nitinvwaran** [comment]
OK, the Phrase structure guidelines for the Hindi treebank seem to also think vaalaa has an aspectual meaning (TAM) in some cases (case III in the treebank guidelines). The good news is that the conllulex file seems to have these tagged AUX indeed and these passed validation.

And the other cases (case I and case II) of vaalaa in the conllulex file are tagged ADP.  The most common case - batti vaalaa - is tagged batti / NOUN vaalaa / ADP. So I'm not sure if we can ignore the nominal 'suffix' as not adpositional. I would label all the remaining non AUX cases as Characteristic ~ Identity.

**Comment by lgessler** [comment]
An aside: how is _about_ as in _She was about to go_ analyzed in English? Here we also something that prima facie looks like an adposition but semantically is clearly an aspectual auxiliary, just line the verbal aspectual sense of _vālā_

**Comment by nschneid** [comment]
In STREUSLE we say about_to has a lexcat of AUX. Definitely not an adposition.

@nitinvwaran Why are you thinking Characteristic~Identity? In "hat vālā man" (the man with a hat), is it presenting some sort of equivalence between the hat and the man?

**Comment by nschneid** [comment]
Is it like if you said "the hat man"? That would be plain Characteristic I think. Restrictiveness/referential uniqueness are not part of the SNACS criteria.

'chaai vaalaa': I don't see how this usage would be an adposition as defined in SNACS, where there is (usually) a semantic relation between two elements. This seems like some sort of complex/derived nominal. Maybe the treebank used P for miscellaneous elements that attach to nouns, but we don't have to adhere to that for lexcat.

**Comment by nitinvwaran** [comment]
> Is it like if you said "the hat man"? That would be plain Characteristic I think. Restrictiveness/referential uniqueness are not part of the SNACS criteria.

OK.

>'chaai vaalaa': I don't see how this usage would be an adposition as defined in SNACS, where there is (usually) a semantic relation between two elements. This seems like some sort of complex/derived nominal. Maybe the treebank used P for miscellaneous elements that attach to nouns, but we don't have to adhere to that for lexcat.

A follow up question to this is what to do with the second case below, in the Hindi LPP corpus:

- 'batti vaala' - lamp man. This is similar to 'chaai vaalaa'.  Translates to: the man (in charge of) the lamps
- 'bati jalaane vaala' - lamp light.INF man. light is the predicate 'to light'.  Translates to: the man who lights the lamps.

vaalaa in the second case immediately follows the verb predicate, but the two terms 'batti vaalaa' and 'batti jalaane vaala' may be equivalent. I think both could be the complex/derived nominal. But would you say in the second case, vaalaa is mediating between 'batti' and 'jalaane'

**Comment by nschneid** [comment]
Could 'batti jalaane' be a compound? Like "lamp-lighting man".

**Comment by lgessler** [comment]
Interesting Nitin, so your parse of _battī jalāne vālā_ is _[battī [jalāne vālā]]_? (I gather this is what you mean when you say "mediating between 'batti' and 'jalaane'".) 

I'd always assumed something more like what Nathan's saying, that it's a compound: _[[battī jalāne] vālā]_. I can't think of any conclusive ways to distinguish off the top of my head, but intuitively it'd be unusual if the verb did not first combine with its argument.

**Comment by lgessler** [comment]
> Maybe, it is mediating instead between the whole VP phrase and the noun being modified?

Right, syntactically, this would be my instinct. I think the UD analysis there is basically right as far as attachments go, but I think what's in question is whether the deprel for the verbal clause (e.g. पहनने in the latter sentence) ought to be `compound` or `amod`. 

(A UD aside: actually, `amod` seems very wrong--"shirt pahanne vālā" seems clausal, but `amod` is only for non-clausal modifiers, so it should be `acl` at least, I think.)

**Comment by nschneid** [comment]
"adjectives such as *bəndərvala* 'one with a pet monkey'...": What makes this an adjective rather than a noun?

**Comment by nitinvwaran** [comment]
Well, this is an example from the Internet as Corpus. The Hindi caption loosely translates to: 'Tyrolean hat and _bəndərvala_ boy". 

![Screen Shot 2022-07-07 at 2 09 53 PM](https://user-images.githubusercontent.com/35068157/177840890-0c685ba9-ae87-4e77-b7e1-804aa77cabcc.png)

And this is the English translation:
![Screen Shot 2022-07-07 at 2 12 41 PM](https://user-images.githubusercontent.com/35068157/177841284-682fc2d3-d5b3-4f6e-b485-3229e62c6bef.png)

The earlier example too, टोपीवाला लड़का, m. the boy wearing a hat. - topivala modifies the boy as adjective.

**Comment by lgessler** [comment]
> "adjectives such as bəndərvala 'one with a pet monkey'...": What makes this an adjective rather than a noun?

I think Kachru is being loose with terminology here, and also revealing that she conceives of uses of _vālā_ like in _bandar vālā_ as AdjPs.

We've already covered some reason why they're alike (both inflect and can modify nominal heads). Another reason to think so is that regular adjectives in Hindi can serve as what classical grammarians would call substantive adjectives, where an adjective is the head of a constituent where you would normally expect an NP, e.g. English _The rich/JJ lack little_, or Hindi (example [from the internet](https://www.amarujala.com/kavya/mere-alfaz/anil-shah-garib-ka-dard)):

```
daulat kī  is       duniyā mɛ̃ gharīb hī  mār     khātā     hɛ̃
wealth GEN this.OBL world  in poor   FOC beating eat.IPFV  are
'In this world of plenty, only the poor are trampled
```

Note how an adjective (_gharīb_) is serving as the subject of the second clause. This is probably one reason why Kachru is analogizing expressions like _bandar vālā_ to adjectives like _gharīb_: both can be syntactically "promoted" to serve as the sole exponents of NPs.

**Comment by nitinvwaran** [comment]
> Is this exhaustive wrt. the syntactic criteria we've been discussing? (And are all of these examples idiomatic, native Hindi speakers?)

I'm not a fully native Hindi speaker, but it looks exhaustive to me.  I'm not certain that 3.b is idiomatic, but maybe Aryaman can comment further.

**Comment by aryamanarora** [comment]
@lgessler no, you can also have an internal AdjP (`nīlā vālā (ādmī)` "(the man) who is blue") or an internal PP or intransitive AdvP (`(mere ghar ke) pīche vālī (saṛak)` "(the road) that's behind (my house)").

**Comment by aryamanarora** [comment]
Also, as much as I love Kachru's grammar the existing descriptive grammars of Hindi are generally very poor at devising a modern syntactic analysis of these kinds of complex phenomena. These `vālā` phrases are absolutely not AdjPs, they take complements in a far too permissive way to be called that. The only formal similarity with AdjPs is the gender/number agreement but other PPs do that too. Many others Ps in Hindi also behave subordinator-like and can take whole clauses as complements.

**Comment by aryamanarora** [comment]
> Hmm, i hadn't thought deeply about how the phrases internally combine :) - But I did look at some UD Hindi treebanks. I found this example below interesting because the vaala follows another verb predicate 'lagnaa' but i don't think the verb is in a compound construction. I think its argument is actually implied / missing. I highlighted the verb predicate + vaalaa in the text:
> 
> ![Screen Shot 2022-07-07 at 11 36 36 AM](https://user-images.githubusercontent.com/35068157/177815443-251ef146-fa24-4f7e-94f7-c411b3c08dd7.png)

Here it is [[[यहाँ लगने]<sub>VP</sub> वाला]<sub>PP</sub> [[तीन दिन]<sub>NP</sub> का]<sub>PP</sub> इज़्तिमा]<sub>NP</sub> "the three-day congregation that will be held here". Takes the VP as a complement, and like a relative clause it is a gapped subject.

**Comment by lgessler** [comment]
> no, you can also have an internal AdjP (nīlā vālā (ādmī) "(the man) who is blue") or an internal PP or intransitive AdvP ((mere ghar ke) pīche vālī (saṛak) "(the road) that's behind (my house)"). 

Ah that's right, hmm... Maybe we should instead distinguish the _vālā_'s complement as clausal or non-clausal, if it's an important one to make.

To the matter at hand though, is this the consensus that's emerging?

1. Aspectual _vālā_: non-SNACS
2. _vālā_ phrase serving as NP: non-SNACS, with the reason being that this is derivational morphology
3. _vālā_ phrase serving as modifier of an NP: SNACS, with the reason being that _vālā_ is mediating a relation between its object (the body of the _vālā_ phrase) and its governor (the noun it is modifying)

**Comment by nitinvwaran** [comment]
> 2\. _vālā_ phrase serving as NP: non-SNACS, with the reason being that this is derivational morphology

vaalaa is pretty much mostly tagged ADP in the treebank. Can derivational morphology get a POS tag? Also, I'm guessing this applies only to 2.b, but what then semantically differentiates 2.b from 2.a, which as a modifier of NP does get a label? To me, both 'batti vaalaa' and 'batti vaalaa aadmi' mean the same thing. 

> 3. _vālā_ phrase serving as modifier of an NP: SNACS, with the reason being that _vālā_ is mediating a relation between its object (the body of the _vālā_ phrase) and its governor (the noun it is modifying)

Agreed, for both the 'internal noun' and 'internal verb' types.

**Comment by nitinvwaran** [comment]
> Note how an adjective (_gharīb_) is serving as the subject of the second clause. This is probably one reason why Kachru is analogizing expressions like _bandar vālā_ to adjectives like _gharīb_: both can be syntactically "promoted" to serve as the sole exponents of NPs.

Actually, bringing this into the 2.a versus 2.b debate, if we say batti vaalaa can replace (substantiatively) batti vaalaa aadmi, that would probably resolve my concern about them being the same thing. But then, how would this substantiative analysis affect the SNACS analysis?

**Comment by lgessler** [comment]
I'm not intimately familiar with SNACS but I think what is and isn't a target is mostly defined by formal, rather than semantic, criteria right? So regardless of how similar _battī vālā ādmī_ and _battī vālā_ in meaning, the fact that they're distinct constructions means we need to consider them both separately. 

So I think our last thing to settle is whether (2b,3b) type _vālā_ phrases are in scope for SNACS, right? @nschneid have there been situations in other languages where an adposition lacks a governor? I can only think of situations where it lacks an object. Here are 2b and 3b again:

```
(2b) Internal noun phrase, serves as nominal phrase
     battī vālā chalā gayā
     lamp  VALA walk  went
     'The lamp-one went away'

(3b) Internal verb phrase, serves as nominal phrase
     battī jalāne   vālā chalā gayā
     lamp  burn.INF VALA walk  went
     'The lamp-burning-one went away'
```

**Comment by nitinvwaran** [comment]
> I'm not intimately familiar with SNACS but I think what is and isn't a target is mostly defined by formal, rather than semantic, criteria right? So regardless of how similar _battī vālā ādmī_ and _battī vālā_ in meaning, the fact that they're distinct constructions means we need to consider them both separately.

Or, we could consider them together under the substantiative adjective analysis that you proposed, which I agree with. We could also consider whether a substantiative adjective that contains an ADP token could get a SNACS label

**Comment by nschneid** [comment]
> have there been situations in other languages where an adposition lacks a (overt?) governor?

None that I can think of. We have things like Approximators in English which actually sort of act like modifiers, but I wouldn't say they lack a governor.

Maybe I'm just not familiar enough with Hindi to get the right intuition but a marker that derives an adjective (substantive or otherwise) from a noun doesn't seem like an adposition to me. The English analogues I can think of are suffixes like -ful (plenty → plentiful). If Hindi has just one word that can be either a postposition or a noun-to-adj deriver, I don't see a problem with assigning a different lexcat to the latter.

**Comment by nitinvwaran** [comment]
> Maybe I'm just not familiar enough with Hindi to get the right intuition but a marker that derives an adjective (substantive or otherwise) from a noun doesn't seem like an adposition to me. The English analogues I can think of are suffixes like -ful (plenty → plentiful). If Hindi has just one word that can be either a postposition or a noun-to-adj deriver, I don't see a problem with assigning a different lexcat to the latter.

If that's the thinking - not considering vaalaa as adpositional - then my thinking is that this needs to apply to both 2.a and 2.b, and 3.a and 3.b, or in other words we shouldn't be considering vaalaa as adpositional in a SNACS sense in the entire corpus. 2.a and 3.a would also derive adjectives and amod phrases (the latter evidenced in the Hindi UD treebanks) from nominals and verb phrases respectively, which may not be in the spirit of being adpositional. 

From a validation perspective because vaalaa is tagged ADP in the entire corpus, I would need to create a specific exception for this, or maybe a specific lexcat (P.VAALAA)?

**Comment by nschneid** [comment]
Or call it `PART`?

**Comment by lgessler** [comment]
> Maybe I'm just not familiar enough with Hindi to get the right intuition but a marker that derives an adjective (substantive or otherwise) from a noun doesn't seem like an adposition to me.

Would be curious for @aryamanarora's opinion here, given that at least in a narrow sense he thinks it's a bad analysis to call _vālā_ phrases "adjectives"

**Comment by nitinvwaran** [comment]
PART works! 

I don't have any more questions here, thanks everyone. My conclusion is to treat all cases of vaalaa as non-SNACS. I don't think a differential treatment for certain cases with an explicit governor, is consistent. If no objections....

**Comment by nschneid** [comment]
@aryamanarora feels strongly that (2a) is postpositional.

**Comment by nitinvwaran** [comment]
I'm OK either way (postposition or no), but i think the treatment should be consistent between 2.a and 2.b - either both are postpositional, or not.

**Comment by lgessler** [comment]
For what my non-native opinion's worth, I'm inclined to agree with Nitin that consistency within (2) and (3) seems right. 

Would it be too difficult to try to set aside a half-hour to talk this out on Zoom in the next couple weeks?

**Comment by svivek** [comment]
My thoughts on this: 
> ```
> (1)  Aspectual
>      ṭren  jāne   vālī hɛ
>      train go.INF VALA is
>      'The train is about to leave'
> ```
Not adposition

> ```
> (2a) Internal noun phrase, modifies nominal head
>      battī vālā ādmī chalā gayā
>      lamp  VALA man  walk  went
>      'The lamp-one man went away'
> ```

Adposition

> ```
> (2b) Internal noun phrase, serves as nominal phrase
>      battī vālā chalā gayā
>      lamp  VALA walk  went
>      'The lamp-one went away'
> ```

Adposition, but the governor is implied.

> ```
> (3a) Internal verb phrase, modifies nominal head
>      battī jalāne   vālā ādmī chalā gayā
>      lamp  burn.INF VALA man  walk  went
>      'The lamp-burning-one man went away'
> ```
Adposition

> ```
> (3b) Internal verb phrase, serves as nominal phrase
>      battī jalāne   vālā chalā gayā
>      lamp  burn.INF VALA walk  went
>      'The lamp-burning-one went away'
> ```

Adposition, but the governor is implied.

**Comment by nschneid** [comment]
When you say "governor is implied" I assume you mean there is an implicit semantic governor, and syntactically, the PP behaves like an NP (some sort of coercion)? Can "battī vālā" be pluralized or case-marked?

I guess we technically have something similar in English with named entities that take the form of PPs ("_Of Mice and Men_ is a novel"). I don't think English has a preposition with a well-established sense for deriving NPs, though.

Matrix-licensed complements (carmls/snacs-guidelines#148) are perhaps broadly similar in being another case of syntax-semantics mismatch.

**Comment by nitinvwaran** [comment]
> Can "battī vālā" be pluralized or case-marked?

Yes to both. Luke had given some examples of case earlier in the thread, where the 'battī vālā' receives oblique case when marked by a post-position 'ko'. 

If it's post-positional, should we go ahead with 'Characteristic'?

**Comment by nschneid** [comment]
> @nschneid in case it's relevant, it might be helpful to note that this _vālā_ morph also uses standard adjective inflections. _vālā_ covers masculine singular nominative, but it would be e.g. _vāle_ for masculine singular oblique:
> 
> ```
> battī vāl -e        ko  batāo ...
> lamp  VALA-M.SG.OBL DAT tell  ...
> 'tell the lampman ...'
> ```

OK, so for those advocating treating (2b) and (3b) as adpositions, would the same analysis hold above? Would it be the sole adposition that can be suffixed with -e (M.SG.OBL)?

**Comment by lgessler** [comment]
> Would it be the sole adposition that can be suffixed with -e (M.SG.OBL)?

From Aryaman above:

> The best evidence for treating this type of vālā as a postposition is that it has similar properties to the genitive kā and the comparison words jaisā, sā. All of these decline in gender/number (like Adjs) to agree with the governor of the PP they project, but they also indicate semantic relations like a PP and obligatorily take a nominal argument like others Ps. Also, semantically vālā is like the inverse of the genitive kā, e.g. "hat vālā man" (the man with a hat) ~ "man kā hat" (the hat of the man).

**Comment by nitinvwaran** [comment]
> OK, so for those advocating treating (2b) and (3b) as adpositions, would the same analysis hold above?

Yes. The inflected vaale form in 'chai vāl-e ko' and 'karne vāl-e ko' appear in (many) more Google search results than the non inflected forms 'chai vālā ko' and 'karne vālā ko'. 

> Would it be the sole adposition that can be suffixed with -e (M.SG.OBL)?

Going to say no, given the genitive postposition ka does indeed inflect for gender and number based on the governor (i'd always thought of them as separate, but we learn something new everyday...). 

'jaisa' and 'sa' could be up for debate...but maybe that's for another thread ('sa' may actually be very similar to vālā - it also makes adjectives out of nouns...)










> Since this thread is long I request that somebody document the justification in the [guidelines](https://arxiv.org/abs/2103.01399). Vālā is mentioned on pp. 39–42:
> 
> > While vālā is not a standard postposition, it mediates between nouns and noun-phrases, assigning one as a CHARACTERISTIC of the other.

Given that restrictive relatives aren't part of the SNACS criteria, i guess vālā is now plain Characteristic for all ADP-tagged vālā in the corpus. If there's consensus, I'll update the corpus accordingly.

**Comment by lgessler** [comment]
FWIW Daniel Chen ran into the same basic problem in Latin/Finnish (adjective-like phrase serving as an NP) and [decided to treat them as annotation targets](http://www.lrec-conf.org/proceedings/lrec2022/pdf/2022.lrec-1.279.pdf):

> Adjectives modifying these token types were not included, as they cannot be considered a governor or object. The exception is when an **adpositionally marked adjective has no noun object present** at all and an implicit noun object along the lines of “thing”, “person”, or “place” can be construed, e.g. the Latin dative plural word _ignotis_, meaning “to the unknown (places)”.

**Comment by nitinvwaran** [comment]
Decisions incorporated in #34 and merged with the master. Pending adjudication of SNACS v2.6 Causer/Force labels, and treatment of sab-se as weak MWE.

**Comment by lgessler** [comment]
Came across this paper: https://www.academia.edu/5145531/Hindi_wala?email_work_card=thumbnail

Author thinks there are at least two homonyms here:

> We thus may appear to have a distinction between two uses of –wala: a lexical –wala (henceforth l-wala) is a word-level suffix that does not trigger OBL versus a syntactic –wala (henceforth s-wala) isa phrasal level clitic that triggers OBL and shows the adjectival agreement pattern typical ofphrasal-level clitics in the language. I will return to this matter at the end of the discussion
